# This is a basic workflow to help you get started with Actions

name: Automatic Deploy Production

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: install package âœ”ï¸
      run: yarn

    # We have to set build dir (nginx serve)
    - name: build package ğŸ“¦
      run: yarn build 
    
    - name: move package for deploy ğŸš•
      run: mv -R build/* ~/build/circle.dimigo.in
      
    - name: deploy packageğŸš€ 
      run: sudo nginx -s reload
      
    # slack is not working now.
    # i want to distinguish success or failed
    - name: Slack Notification failed ğŸ™…
      if: failure()
      uses: rtCamp/action-slack-notify@v2.0.0
      env:
        SLACK_CHANNEL: github-subscription
        SLACK_COLOR: '#FF0000'
        SLACK_ICON: http://github.com/dimigoin.png?size=48
        SLACK_MESSAGE: 'í”„ë¡ íŠ¸ì—”ë“œì— ëŒ€í•œ ë°°í¬ê°€ ì‹¤íŒ¨í–ˆì–´ìš” ! :cry:'
        SLACK_TITLE: Deploy failed
        SLACK_USERNAME: Dimigoin auto deploy bot
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

    - name: Slack Notification success ğŸ™†
      if: success()
      uses: rtCamp/action-slack-notify@v2.0.0
      env:
        SLACK_CHANNEL: github-subscription
        SLACK_COLOR: '#04ff00'
        SLACK_ICON: http://github.com/dimigoin.png?size=48
        SLACK_MESSAGE: 'í”„ë¡ íŠ¸ì—”ë“œì— ëŒ€í•œ ë°°í¬ê°€ ì™„ë£Œë˜ì—ˆì–´ìš” ! :rocket:'
        SLACK_TITLE: Deploy Success
        SLACK_USERNAME: Dimigoin auto deploy bot
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
